graph TD
    HPC["Hardware Performance Counters"]--> SDK["OpenTelemetry SDK"]
    SDK --> |HTTP or gRPC| COLLECTOR
    COLLECTOR["Jaeger Collector"] --> STORE[Storage]
    COLLECTOR --> |gRPC| PLUGIN[Storage Plugin]
    COLLECTOR --> |gRPC/sampling| SDK
    PLUGIN --> STORE
    QUERY[Jaeger Query Service] --> STORE
    QUERY --> |gRPC| PLUGIN
    UI[Jaeger UI] --> |HTTP| QUERY

    subgraph Application Host
        subgraph User Application
            HPC
            SDK
        end
    end
